### ISSUE TITLE
Tendermint Readings

### ISSUE THREAD

**Issue by Mikerah** [hashcloak/katzenmint-pki#10]
- [x] : https://tendermint.com/static/docs/tendermint.pdf
- [x] : https://arxiv.org/abs/1807.04938
- [x] : https://docs.tendermint.com/master/
- [x] : https://atrium.lib.uoguelph.ca/xmlui/bitstream/handle/10214/9769/Buchman_Ethan_201606_MAsc.pdf

Take notes and post them as comments to this issue.

**Comment by sebohe** [comment]
https://hackmd.io/n5c1BJ0RRI-M3SghwGVTrA
https://hackmd.io/GPouJhU0RGyiEJJ-LhTOIg
https://hackmd.io/UX_gM7lVRwqvwD19R1NO6g
